name: "PvPoints"
main: "com.jackwilsdon.PvPoints.PvPointsPlugin"
version: "1.3.1"
description: "Track yo' kills!"
author: "Jack Wilsdon (jackwilsdon)"
website: "http://jackwilsdon.tk"

commands:
    pvpoints:
        description: Multi-use PvPoints command
        usage: /pvpoints help
        aliases: ["pv"]